version: 2.1
orbs:
  docker: circleci/docker@1.2.0
jobs:
  server_tests:
    working_directory: ~/app/server
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout:
          path: ~/app/
      - run:
          name: npm-install
          command: npm install
      - run:
          name: test
          command: npm test   
  client_tests:
    working_directory: ~/app/client
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout:
          path: ~/app/
      - run:
          name: npm-install
          command: npm install
      - run:
          name: test
          command: npm test -- --watchAll=false
  build_server_image:
    working_directory: ~/app/
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker	  
      - run:
          name: build server image
          command: docker build -t karen2035/server:0.1 -f server/Dockerfile server
      - run:
          name: docker login
          command: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run:
          name: docker push
          command: docker push karen2035/server:0.1
  build_client_image:
    working_directory: ~/app/
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker	  
      - run:
          name: build client image
          command: docker build -t karen2035/client:0.1 -f client/Dockerfile client
      - run:
          name: docker login
          command: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run:
          name: docker push
          command: docker push karen2035/client:0.1

workflows:
  version: 2
  run_tests_and_deploy:
    jobs:
      - server_tests
      - client_tests      
      - build_server_image:
          requires:
          - server_tests
          filters:
              branches:
                only:
                  - master
      - build_client_image:
          requires:
          - client_tests
          filters:
              branches:
                only:
                  - master
